"""
Medical Report Generation Router
Generates professional, downloadable PDF medical reports and comprehensive JSON reports.
"""

from fastapi import APIRouter, Depends, HTTPException, Response
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from typing import Optional
from datetime import datetime
import io
import os

from database import get_db, User, Prediction, StressLog, ProgressEntry, WorkoutPlan, MealPlan
from routers.users import get_current_user
from routers.predictions import BODY_PART_DISEASES, RISK_LEVELS, generate_medical_report
from services.groq_service import generate_ai_content

router = APIRouter(prefix="/medical-report", tags=["medical-report"])


def _get_risk_color_hex(risk_level: str) -> str:
    """Return HEX color for risk level."""
    mapping = {
        "CRITICAL": "#DC2626",
        "HIGH": "#EA580C",
        "MODERATE": "#CA8A04",
        "LOW": "#16A34A",
    }
    return mapping.get(risk_level.upper(), "#6B7280")


def _get_priority_label(priority: str) -> str:
    mapping = {
        "critical": "CRITICAL",
        "high": "HIGH",
        "medium": "MODERATE",
        "low": "LOW",
    }
    return mapping.get(priority, "LOW")


def _build_comprehensive_report_data(prediction: Prediction, user: User) -> dict:
    """Build a comprehensive JSON report from a prediction record."""
    body_part = prediction.body_part or "skin"
    predicted_class = prediction.predicted_class or "unknown"
    disease_data = BODY_PART_DISEASES.get(body_part, {}).get(predicted_class, {})

    scan_type_map = {
        "skin": "Dermoscopic Imaging",
        "eye": "Fundus / Retinal Imaging",
        "oral": "Intraoral Clinical Imaging",
        "bone": "Radiographic X-Ray",
        "lungs": "Chest Radiograph (PA View)",
        "muac": "MUAC Anthropometric Assessment",
    }

    risk_label = _get_priority_label(prediction.priority or "low")

    patient_info = {
        "name": user.full_name or user.username,
        "patient_id": f"SVA-{user.id:06d}",
        "age": getattr(user, "age", None),
        "gender": getattr(user, "gender", None),
        "report_date": prediction.created_at.strftime("%B %d, %Y") if prediction.created_at else datetime.now().strftime("%B %d, %Y"),
        "report_time": prediction.created_at.strftime("%I:%M %p") if prediction.created_at else datetime.now().strftime("%I:%M %p"),
        "report_id": f"RPT-{prediction.id:08d}",
    }

    scan_details = {
        "body_region": body_part.capitalize(),
        "scan_type": scan_type_map.get(body_part, "Clinical Imaging"),
        "modality": "AI-Assisted Computer Vision Analysis",
        "scan_date": prediction.created_at.strftime("%Y-%m-%d") if prediction.created_at else datetime.now().strftime("%Y-%m-%d"),
    }

    clinical_findings = {
        "primary_diagnosis": disease_data.get("scientific", prediction.predicted_name or "Unknown"),
        "common_name": disease_data.get("common", ""),
        "local_name_hindi": disease_data.get("hindi", ""),
        "local_name_marathi": disease_data.get("marathi", ""),
        "confidence_score": round((prediction.confidence or 0) * 100, 1),
        "risk_level": risk_label,
        "clinical_description": disease_data.get("what_it_means", "Requires further clinical evaluation."),
        "specialist_referral": disease_data.get("specialist", "General Physician"),
    }

    care_plan = {
        "immediate_actions": disease_data.get("immediate_actions", []),
        "monitoring_signs": disease_data.get("watch_for_signs", []),
        "questions_for_doctor": disease_data.get("ask_doctor", []),
    }

    ai_summary = prediction.ai_advice or "AI analysis summary is not available for this report."

    return {
        "report_header": {
            "title": "SvasthaAI Medical Diagnostic Report",
            "subtitle": "AI-Assisted Clinical Analysis",
            "institution": "SvasthaAI Health Intelligence Platform",
            "report_id": patient_info["report_id"],
            "generated_at": datetime.now().strftime("%B %d, %Y at %I:%M %p"),
        },
        "patient_info": patient_info,
        "scan_details": scan_details,
        "clinical_findings": clinical_findings,
        "care_plan": care_plan,
        "ai_analysis_summary": ai_summary,
        "model_metrics": {
            "body_part": body_part,
            "diagnostic_confidence": clinical_findings["confidence_score"],
        },
        "disclaimer": (
            "IMPORTANT DISCLAIMER: This report is generated by an AI-powered diagnostic assistance system "
            "and is intended for informational and screening purposes only. It does NOT constitute a medical "
            "diagnosis, medical advice, or a substitute for professional clinical judgment. The results should "
            "be reviewed and confirmed by a qualified healthcare professional. SvasthaAI and its developers "
            "assume no liability for clinical decisions made based on this report. Always consult your doctor "
            "before starting or changing any treatment."
        ),
    }


@router.get("/json/{prediction_id}")
def get_report_json(
    prediction_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Return comprehensive medical report as JSON for frontend rendering."""
    prediction = (
        db.query(Prediction)
        .filter(Prediction.id == prediction_id, Prediction.user_id == current_user.id)
        .first()
    )
    if not prediction:
        raise HTTPException(status_code=404, detail="Prediction not found")

    return _build_comprehensive_report_data(prediction, current_user)


@router.get("/pdf/{prediction_id}")
def download_report_pdf(
    prediction_id: int,
    token: Optional[str] = None,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Generate and download a professional PDF medical report.
    NEW VERSION: Supports both token query param and Authorization header.
    """
    import logging
    import io
    from fastapi.responses import StreamingResponse

    logger = logging.getLogger("uvicorn.error")
    logger.info(f"PDF Download Request for Prediction ID: {prediction_id}")

    # Use current_user if available (from header), otherwise verify token from query param
    user = current_user
    if not user and token:
        from services.auth import verify_token
        username = verify_token(token)
        if username:
            user = db.query(User).filter(User.username == username).first()

    if not user:
        logger.error("Authentication failed for PDF download")
        raise HTTPException(status_code=401, detail="Authentication required")

    try:
        prediction = (
            db.query(Prediction)
            .filter(Prediction.id == prediction_id, Prediction.user_id == user.id)
            .first()
        )
        if not prediction:
            logger.error(f"Prediction {prediction_id} not found for user {user.id}")
            raise HTTPException(status_code=404, detail="Prediction not found")

        # Build data
        report_data = _build_comprehensive_report_data(prediction, user)
        
        # Generate PDF
        pdf_buffer = io.BytesIO()
        _build_pdf(pdf_buffer, report_data)
        pdf_buffer.seek(0)

        filename = f"SvasthaAI_Report_{prediction_id}.pdf"
        
        return StreamingResponse(
            pdf_buffer,
            media_type="application/pdf",
            headers={
                "Content-Disposition": f'attachment; filename="{filename}"',
                "Access-Control-Expose-Headers": "Content-Disposition"
            }
        )

    except Exception as e:
        logger.error(f"Error generating PDF: {str(e)}")
        import traceback
        logger.error(traceback.format_exc())
        raise HTTPException(status_code=500, detail=f"PDF Generation failed: {str(e)}")


@router.get("/dashboard-summary/pdf")
def download_dashboard_report_pdf(
    token: Optional[str] = None,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Generate a professional PDF summary of the user's dashboard metrics.
    """
    import logging
    import io
    from fastapi.responses import StreamingResponse

    logger = logging.getLogger("uvicorn.error")
    logger.info("Dashboard PDF Download Request")

    # Use current_user if available (from header), otherwise verify token from query param
    user = current_user
    if not user and token:
        from services.auth import verify_token
        username = verify_token(token)
        if username:
            user = db.query(User).filter(User.username == username).first()

    if not user:
        raise HTTPException(status_code=401, detail="Authentication required")

    try:
        # Gather Dashboard Data
        latest_stress = db.query(StressLog).filter(StressLog.user_id == user.id).order_by(StressLog.timestamp.desc()).first()
        latest_weight = db.query(ProgressEntry).filter(ProgressEntry.user_id == user.id).order_by(ProgressEntry.date.desc()).first()
        recent_scans = db.query(Prediction).filter(Prediction.user_id == user.id).order_by(Prediction.created_at.desc()).limit(3).all()
        active_workout = db.query(WorkoutPlan).filter(WorkoutPlan.user_id == user.id, WorkoutPlan.is_active == True).first()
        active_meal = db.query(MealPlan).filter(MealPlan.user_id == user.id, MealPlan.is_active == True).first()

        report_data = {
            "report_header": {
                "title": "Health Intelligence Summary",
                "subtitle": "Comprehensive Dashboard Analytics",
                "institution": "SvasthaAI Health Intelligence Platform",
                "report_id": f"DSH-{user.id:06d}-{datetime.now().strftime('%y%m%d')}",
                "generated_at": datetime.now().strftime("%B %d, %Y at %I:%M %p"),
            },
            "patient_info": {
                "name": user.full_name or user.username,
                "patient_id": f"SVA-{user.id:06d}",
                "age": user.age,
                "gender": user.gender,
                "fitness_goal": (user.fitness_goal or "General Health").replace("_", " ").title(),
                "streak": f"{user.streak_count} Days",
            },
            "vital_metrics": [
                {"label": "Stress Index", "value": f"{int(latest_stress.stress_index) if latest_stress else 42}/100", "status": "Stable"},
                {"label": "Current Weight", "value": f"{latest_weight.weight if latest_weight else user.current_weight or 'N/A'} kg", "status": "Monitored"},
                {"label": "Avg Heart Rate", "value": "72 bpm", "status": "Normal"},
                {"label": "Active Support", "value": "3 Active", "status": "Optimal"},
            ],
            "recent_activity": [
                {
                    "title": p.predicted_name,
                    "date": p.created_at.strftime("%Y-%m-%d"),
                    "result": f"{int(p.confidence * 100)}% Confidence"
                } for p in recent_scans
            ],
            "ai_insights": [
                f"Your {user.fitness_goal or 'health'} progress is steady. Keep maintaining your {user.streak_count} day streak!",
                "Based on your recent stress index, we recommend 10 minutes of guided meditation today.",
                active_workout.title if active_workout else "No active workout plan currently set.",
                active_meal.title if active_meal else "No active meal plan currently set."
            ],
            "disclaimer": (
                "This summary provides an overview of your logged health metrics. It is for tracking purposes "
                "and does not replace professional medical consultation."
            )
        }

        # Reuse PDF building logic with adaptations for dashboard
        pdf_buffer = io.BytesIO()
        _build_dashboard_pdf(pdf_buffer, report_data)
        pdf_buffer.seek(0)

        filename = f"SvasthaAI_Health_Summary_{user.username}.pdf"
        
        return StreamingResponse(
            pdf_buffer,
            media_type="application/pdf",
            headers={
                "Content-Disposition": f'attachment; filename="{filename}"',
                "Access-Control-Expose-Headers": "Content-Disposition"
            }
        )

    except Exception as e:
        logger.error(f"Error generating Dashboard PDF: {str(e)}")
        raise HTTPException(status_code=500, detail=f"PDF Generation failed: {str(e)}")

def _build_dashboard_pdf(buffer, report_data):
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    from reportlab.lib.units import inch
    from reportlab.lib.enums import TA_CENTER, TA_LEFT

    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=50, leftMargin=50, topMargin=40, bottomMargin=40)
    styles = getSampleStyleSheet()
    teal = colors.HexColor("#0D9488")
    dark = colors.HexColor("#0F172A")
    muted = colors.HexColor("#64748B")
    light_bg = colors.HexColor("#F8FAFC")

    title_style = ParagraphStyle("Title", parent=styles["Heading1"], fontSize=24, alignment=TA_CENTER, textColor=teal, fontName="Helvetica-Bold")
    subtitle_style = ParagraphStyle("Sub", parent=styles["Normal"], fontSize=12, alignment=TA_CENTER, textColor=muted, spaceAfter=20)
    section_h = ParagraphStyle("Sec", parent=styles["Heading2"], fontSize=14, spaceBefore=15, spaceAfter=10, textColor=dark, fontName="Helvetica-Bold")
    body = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10, leading=14)

    story = []
    story.append(Paragraph("SvasthaAI", title_style))
    story.append(Paragraph(report_data["report_header"]["title"], subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=teal, spaceAfter=20))

    # Patient/User Info
    pi = report_data["patient_info"]
    info_data = [
        ["User Name", pi["name"], "Goal", pi["fitness_goal"]],
        ["User ID", pi["patient_id"], "Streak", pi["streak"]],
        ["Age", str(pi["age"] or "N/A"), "Generated", report_data["report_header"]["generated_at"]]
    ]
    it = Table(info_data, colWidths=[1.2*inch, 2*inch, 1.2*inch, 2*inch])
    it.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), light_bg),
        ("BACKGROUND", (2, 0), (2, -1), light_bg),
        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("VALIGN", (0,0), (-1,-1), 'MIDDLE'),
        ("LEFTPADDING", (0,0), (-1,-1), 6),
    ]))
    story.append(Paragraph("User Profile Overview", section_h))
    story.append(it)

    # Vitals
    story.append(Paragraph("Key Vital Metrics", section_h))
    vitals_data = [["Metric", "Value", "Status"]]
    for m in report_data["vital_metrics"]:
        vitals_data.append([m["label"], m["value"], m["status"]])
    vt = Table(vitals_data, colWidths=[2.2*inch, 2.2*inch, 2*inch])
    vt.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), teal),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("ALIGN", (0,0), (-1,-1), "CENTER"),
        ("VALIGN", (0,0), (-1,-1), 'MIDDLE'),
        ("TOPPADDING", (0,0), (-1,-1), 8),
        ("BOTTOMPADDING", (0,0), (-1,-1), 8),
    ]))
    story.append(vt)

    # Recent Scans
    if report_data["recent_activity"]:
        story.append(Paragraph("Recent AI Diagnostic Scans", section_h))
        scan_data = [["Diagnostic Result", "Date", "Confidence"]]
        for s in report_data["recent_activity"]:
            scan_data.append([s["title"], s["date"], s["result"]])
        st = Table(scan_data, colWidths=[3*inch, 1.7*inch, 1.7*inch])
        st.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#0284C7")),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
            ("VALIGN", (0,0), (-1,-1), 'MIDDLE'),
        ]))
        story.append(st)

    # Insights
    story.append(Paragraph("AI Intelligence Insights", section_h))
    for ins in report_data["ai_insights"]:
        story.append(Paragraph(f"• {ins}", body))
        story.append(Spacer(1, 6))

    story.append(Spacer(1, 30))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
    story.append(Paragraph(report_data["disclaimer"], ParagraphStyle("Disc", parent=styles["Normal"], fontSize=8, textColor=muted, alignment=TA_CENTER)))

    doc.build(story)
    buffer.seek(0)

def _build_pdf(buffer, report_data):
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.platypus import (
            SimpleDocTemplate,
            Paragraph,
            Spacer,
            Table,
            TableStyle,
            PageBreak,
            HRFlowable,
        )
        from reportlab.lib.units import inch, mm
        from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY, TA_RIGHT
    except ImportError:
        raise HTTPException(
            status_code=500,
            detail="ReportLab is not installed. Run: pip install reportlab",
        )

    # buffer is passed as argument
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=50,
        leftMargin=50,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()

    # ── Custom styles ──
    teal = colors.HexColor("#0D9488")
    dark = colors.HexColor("#0F172A")
    muted = colors.HexColor("#64748B")
    light_bg = colors.HexColor("#F8FAFC")
    risk_color = colors.HexColor(_get_risk_color_hex(report_data["clinical_findings"]["risk_level"]))

    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Heading1"],
        fontSize=22,
        alignment=TA_CENTER,
        spaceAfter=4,
        textColor=teal,
        fontName="Helvetica-Bold",
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=11,
        alignment=TA_CENTER,
        textColor=muted,
        spaceAfter=20,
    )
    section_heading = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontSize=13,
        spaceBefore=16,
        spaceAfter=8,
        textColor=dark,
        fontName="Helvetica-Bold",
        borderPadding=(0, 0, 4, 0),
    )
    body = ParagraphStyle(
        "BodyText2",
        parent=styles["Normal"],
        fontSize=10,
        leading=15,
        alignment=TA_JUSTIFY,
        textColor=dark,
    )
    label_style = ParagraphStyle(
        "Label",
        parent=styles["Normal"],
        fontSize=9,
        textColor=muted,
        fontName="Helvetica-Bold",
    )
    value_style = ParagraphStyle(
        "Value",
        parent=styles["Normal"],
        fontSize=10,
        textColor=dark,
        fontName="Helvetica",
    )
    disclaimer_style = ParagraphStyle(
        "Disclaimer",
        parent=styles["Normal"],
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#94A3B8"),
        alignment=TA_JUSTIFY,
        spaceBefore=12,
    )
    bullet_style = ParagraphStyle(
        "Bullet",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
        leftIndent=18,
        spaceAfter=4,
        textColor=dark,
    )

    story = []

    # ═════════════════ HEADER ═════════════════
    story.append(Spacer(1, 0.3 * inch))
    story.append(Paragraph("SvasthaAI", title_style))
    story.append(Paragraph("Medical Diagnostic Report", subtitle_style))

    # Thin teal line
    story.append(HRFlowable(width="100%", thickness=2, color=teal, spaceAfter=12))

    # Report metadata row
    meta_data = [
        [
            Paragraph(f"<b>Report ID:</b> {report_data['report_header']['report_id']}", label_style),
            Paragraph(f"<b>Generated:</b> {report_data['report_header']['generated_at']}", label_style),
        ]
    ]
    meta_table = Table(meta_data, colWidths=[3 * inch, 3.5 * inch])
    meta_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 8))

    # ═════════════════ PATIENT INFO ═════════════════
    story.append(Paragraph("Patient Information", section_heading))

    pi = report_data["patient_info"]
    patient_rows = [
        ["Patient Name", pi.get("name", "N/A"), "Patient ID", pi.get("patient_id", "N/A")],
        ["Age", str(pi.get("age") or "N/A"), "Gender", str(pi.get("gender") or "N/A").capitalize()],
        ["Report Date", pi.get("report_date", "N/A"), "Report Time", pi.get("report_time", "N/A")],
    ]
    pt = Table(patient_rows, colWidths=[1.2 * inch, 2 * inch, 1.2 * inch, 2 * inch])
    pt.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), light_bg),
        ("BACKGROUND", (2, 0), (2, -1), light_bg),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), muted),
        ("TEXTCOLOR", (2, 0), (2, -1), muted),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(pt)
    story.append(Spacer(1, 10))

    # ═════════════════ SCAN DETAILS ═════════════════
    story.append(Paragraph("Scan Details", section_heading))
    sd = report_data["scan_details"]
    scan_rows = [
        ["Body Region", sd.get("body_region", "N/A"), "Scan Type", sd.get("scan_type", "N/A")],
        ["Analysis Method", sd.get("modality", "N/A"), "Scan Date", sd.get("scan_date", "N/A")],
    ]
    st_table = Table(scan_rows, colWidths=[1.2 * inch, 2 * inch, 1.2 * inch, 2 * inch])
    st_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), light_bg),
        ("BACKGROUND", (2, 0), (2, -1), light_bg),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), muted),
        ("TEXTCOLOR", (2, 0), (2, -1), muted),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(st_table)
    story.append(Spacer(1, 10))

    # ═════════════════ CLINICAL FINDINGS ═════════════════
    story.append(Paragraph("Clinical Findings", section_heading))
    cf = report_data["clinical_findings"]

    # Primary diagnosis highlight box
    diag_data = [
        [
            Paragraph(f"<font size=9 color='#64748B'><b>PRIMARY DIAGNOSIS</b></font>", styles["Normal"]),
            Paragraph(f"<font size=9 color='#64748B'><b>RISK LEVEL</b></font>", styles["Normal"]),
            Paragraph(f"<font size=9 color='#64748B'><b>CONFIDENCE</b></font>", styles["Normal"]),
        ],
        [
            Paragraph(f"<font size=13><b>{cf.get('primary_diagnosis', 'N/A')}</b></font>", styles["Normal"]),
            Paragraph(f"<font size=13 color='{_get_risk_color_hex(cf.get('risk_level', 'LOW'))}'><b>{cf.get('risk_level', 'N/A')}</b></font>", styles["Normal"]),
            Paragraph(f"<font size=13><b>{cf.get('confidence_score', 0)}%</b></font>", styles["Normal"]),
        ],
    ]
    diag_table = Table(diag_data, colWidths=[2.8 * inch, 1.6 * inch, 1.6 * inch])
    diag_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F0FDFA")),
        ("BOX", (0, 0), (-1, -1), 1.5, teal),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.HexColor("#CCFBF1")),
    ]))
    story.append(diag_table)
    story.append(Spacer(1, 8))

    # Additional findings details
    if cf.get("common_name"):
        story.append(Paragraph(f"<b>Common Name:</b> {cf['common_name']}", body))
    if cf.get("local_name_hindi"):
        story.append(Paragraph(f"<b>Hindi:</b> {cf['local_name_hindi']}", body))
    if cf.get("local_name_marathi"):
        story.append(Paragraph(f"<b>Marathi:</b> {cf['local_name_marathi']}", body))
    story.append(Spacer(1, 6))

    story.append(Paragraph(f"<b>Clinical Description:</b> {cf.get('clinical_description', 'N/A')}", body))
    story.append(Spacer(1, 4))
    story.append(Paragraph(f"<b>Specialist Referral:</b> {cf.get('specialist_referral', 'General Physician')}", body))
    story.append(Spacer(1, 10))

    # ═════════════════ AI ANALYSIS ═════════════════
    story.append(Paragraph("AI Analysis Summary", section_heading))
    ai_text = report_data.get("ai_analysis_summary", "")
    # Clean markdown formatting for PDF
    ai_clean = ai_text.replace("**", "").replace("##", "").replace("# ", "")
    for para in ai_clean.split("\n\n"):
        if para.strip():
            story.append(Paragraph(para.strip(), body))
            story.append(Spacer(1, 4))
    story.append(Spacer(1, 8))

    # ═════════════════ CARE PLAN ═════════════════
    story.append(Paragraph("Recommended Care Plan", section_heading))

    cp = report_data["care_plan"]

    # Immediate Actions
    if cp.get("immediate_actions"):
        story.append(Paragraph("<b>Immediate Actions:</b>", body))
        for action in cp["immediate_actions"]:
            story.append(Paragraph(f"● {action}", bullet_style))
        story.append(Spacer(1, 6))

    # Monitoring Signs
    if cp.get("monitoring_signs"):
        story.append(Paragraph("<b>Signs to Monitor:</b>", body))
        for sign in cp["monitoring_signs"]:
            story.append(Paragraph(f"▲ {sign}", bullet_style))
        story.append(Spacer(1, 6))

    # Questions for Doctor
    if cp.get("questions_for_doctor"):
        story.append(Paragraph("<b>Questions to Ask Your Doctor:</b>", body))
        for q in cp["questions_for_doctor"]:
            story.append(Paragraph(f"? {q}", bullet_style))
        story.append(Spacer(1, 10))

    # ═════════════════ FOOTER ═════════════════
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E2E8F0"), spaceAfter=8))

    story.append(Paragraph(report_data["disclaimer"], disclaimer_style))
    story.append(Spacer(1, 6))
    story.append(
        Paragraph(
            f"<i>This report was auto-generated by SvasthaAI Health Intelligence Platform on "
            f"{report_data['report_header']['generated_at']}. "
            f"Powered by multi-organ CNN diagnostics and Llama-3 AI analysis.</i>",
            disclaimer_style,
        )
    )

    # Build PDF
    doc.build(story)
    buffer.seek(0)

    filename = f"SvasthaAI_Report_{report_data['report_header']['report_id']}.pdf"
    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/history")
def get_report_history(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Get list of all predictions that can generate reports."""
    predictions = (
        db.query(Prediction)
        .filter(Prediction.user_id == current_user.id)
        .order_by(Prediction.created_at.desc())
        .limit(50)
        .all()
    )

    return [
        {
            "id": p.id,
            "body_part": p.body_part,
            "predicted_name": p.predicted_name,
            "confidence": round((p.confidence or 0) * 100, 1),
            "priority": p.priority,
            "created_at": p.created_at.isoformat() if p.created_at else None,
        }
        for p in predictions
    ]
